#Updated active run folder context
#Wed Jul 15 08:29:50 IST 2026
merge.start_marker=// START_MERGE
source.folder=test_workspace/v1
threads=10
enhancement.merge.enabled=true
compare.output_dir=/Volumes/Study/Projects/java-analyzer-project/java_analysis_output/run_20260714_111020
enhancement.compare.enabled=true
active.run_folder=/Volumes/Study/Projects/java-analyzer-project/java_analysis_output/run_20260715_082950
merge.end_marker=// END_MERGE
