#!/bin/bash
if [ -d "/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin" ]; then
    export PATH="/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin:$PATH"
fi
echo "=================================================="
echo "              JAVALENS TEST SUITE RUN             "
echo "=================================================="

# Clean and create directories
rm -rf test_out && mkdir -p test_out
[ -f javalens.conf ] && cp javalens.conf javalens.conf.test_bak
[ -f analyzer.properties ] && cp analyzer.properties analyzer.properties.test_bak
[ -f java_report_data.js ] && cp java_report_data.js java_report_data.js.test_bak

# 1. Compile codebase
echo -e "\n1. Compiling codebase..."
./build.sh
if [ $? -ne 0 ]; then
    echo "Build failed. Aborting tests."
    exit 1
fi

# Reset test files
echo "Resetting test files..."
rm -rf test_workspace/v1_backup && cp -r test_workspace/v1 test_workspace/v1_backup

# 2. Test Analyze Mode
echo -e "\n2. Running Analyze Mode on test_workspace/v1..."
./run.sh --mode analyze --source test_workspace/v1 --output-dir test_out/analyze_out

echo -e "\nAttributes Output CSV:"
cat test_out/analyze_out/run_*/java_attributes.csv | head -n 5
echo -e "\nMethods Output CSV:"
cat test_out/analyze_out/run_*/java_methods.csv | head -n 5

# 3. Test Compare Mode with --existing and --generated flags
echo -e "\n3. Running Compare Mode between existing (v1) and newly generated (v2)..."
./run.sh --mode compare --existing test_workspace/v1 --generated test_workspace/v2 --output-dir test_out/compare_out

echo -e "\nAttributes Compare Delta CSV:"
cat test_out/compare_out/run_*/comparison_attributes.csv | head -n 5
echo -e "\nMethods Compare Delta CSV:"
cat test_out/compare_out/run_*/comparison_methods.csv | head -n 5

# 4. Test Merge Mode with file preservation
echo -e "\n4. Running Merge Mode (Existing Java Files -> Newly Generated Java Files)..."
echo -e "package com.example;\npublic class ExtraV1Only {\n    private String note = \"Exclusive to existing folder\";\n}\n" > test_workspace/v1/ExtraV1Only.java

./run.sh --mode merge --existing test_workspace/v1 --generated test_workspace/v2 --output-dir test_out/merge_out --start-marker "// START_MERGE" --end-marker "// END_MERGE"

MERGED_DIR=$(find test_out/merge_out/run_* -type d -name "merged" | head -n 1)
if [ -z "$MERGED_DIR" ]; then
    MERGED_DIR=$(ls -d test_out/merge_out/run_* | head -n 1)
fi

echo -e "\nMerged output MyClass.java contents:"
cat "$MERGED_DIR/MyClass.java"

echo -e "\nVerified existing-only file preserved in output folder (ExtraV1Only.java):"
cat "$MERGED_DIR/ExtraV1Only.java"

rm -f test_workspace/v1/ExtraV1Only.java

# 5. Test Report Mode (Script run = CSV only!)
echo -e "\n5. Running Unified Report Mode (Script run must produce CSV reports only)..."
./run.sh --mode report --existing test_workspace/v1 --generated test_workspace/v2 --output-dir test_out/report_out

REPORT_RUN_DIR=$(ls -d test_out/report_out/run_* | head -n 1)
echo -e "\nReports generated in output run folder ($REPORT_RUN_DIR):"
ls -lh "$REPORT_RUN_DIR"

# Verify CSV reports exist
if [ -f "$REPORT_RUN_DIR/javalens_report.csv" ]; then
    echo "✔ PASS: javalens_report.csv exists."
else
    echo "❌ FAIL: javalens_report.csv missing!"
    exit 1
fi

if [ -f "$REPORT_RUN_DIR/javalens_summary.txt" ]; then
    echo "✔ PASS: javalens_summary.txt exists."
    cat "$REPORT_RUN_DIR/javalens_summary.txt"
else
    echo "❌ FAIL: javalens_summary.txt missing!"
    exit 1
fi

# Verify non-CSV reports were NOT generated by the script run (lazy generation)
if [ -f "$REPORT_RUN_DIR/javalens_report.xlsx" ] || [ -f "$REPORT_RUN_DIR/javalens_report.json" ] || [ -f "$REPORT_RUN_DIR/javalens_report.html" ]; then
    echo "❌ FAIL: Non-CSV reports should NOT be generated during script run! They must be on-demand."
    exit 1
else
    echo "✔ PASS: Lazy generation verified - no xlsx/json/html reports created during script run."
fi

# 6. Test On-Demand Excel (.xlsx), JSON, and HTML Generation
echo -e "\n6. Testing On-Demand Excel (.xlsx) Report Generation..."
java -cp javalens.jar com.javalens.engine.ReportGenerator "$REPORT_RUN_DIR" xlsx

if [ -f "$REPORT_RUN_DIR/javalens_report.xlsx" ]; then
    EXCEL_SIZE=$(wc -c < "$REPORT_RUN_DIR/javalens_report.xlsx" | tr -d ' ')
    echo "✔ PASS: Excel file created successfully (size: ${EXCEL_SIZE} bytes)."
else
    echo "❌ FAIL: Excel file not created!"
    exit 1
fi

echo -e "\nTesting On-Demand JSON and HTML Report Generation..."
java -cp javalens.jar com.javalens.engine.ReportGenerator "$REPORT_RUN_DIR" json
java -cp javalens.jar com.javalens.engine.ReportGenerator "$REPORT_RUN_DIR" html

if [ -f "$REPORT_RUN_DIR/javalens_report.json" ] && [ -f "$REPORT_RUN_DIR/javalens_report.html" ]; then
    echo "✔ PASS: On-demand JSON and HTML reports generated successfully."
else
    echo "❌ FAIL: On-demand JSON or HTML missing!"
    exit 1
fi

# Verify the xlsx archive contents
echo -e "\nVerifying Excel (.xlsx) OpenXML archive structure:"
unzip -l "$REPORT_RUN_DIR/javalens_report.xlsx"

# 7. Test Configuration .conf File Mode and directory hygiene
echo -e "\n7. Testing .conf configuration file workflow & directory hygiene..."
./run.sh --existing test_workspace/v1 --generated test_workspace/v2 --output-dir test_out/conf_test_out --threads 4 --save-config test_out/custom.conf
echo "Saved config file output.dir check:"
grep "output.dir=" test_out/custom.conf
grep "existing.path=" test_out/custom.conf
grep "generated.path=" test_out/custom.conf

if grep -q "output.dir=test_out/conf_test_out/run_" test_out/custom.conf; then
    echo "❌ FAIL: output.dir was polluted with run_ folder!"
    exit 1
else
    echo "✔ PASS: output.dir preserved cleanly as base directory."
fi

# Restore test files
rm -rf test_workspace/v1 && cp -r test_workspace/v1_backup test_workspace/v1 && rm -rf test_workspace/v1_backup
rm -rf test_out
[ -f javalens.conf.test_bak ] && mv javalens.conf.test_bak javalens.conf
[ -f analyzer.properties.test_bak ] && mv analyzer.properties.test_bak analyzer.properties
[ -f java_report_data.js.test_bak ] && mv java_report_data.js.test_bak java_report_data.js

echo -e "\n=================================================="
echo "              TEST SUITE CONCLUDED                "
echo "=================================================="
